name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - test
      id: step1
      run: ls -la

    - name: Step 2 - Set up Node.js
      id: step2
      run: pwd

    - name: Step 3 - Install dependencies
      id: step3
      run: npm ci

    - name: Step 4 - Run tests
      id: step4
      run: ping 8.8.8.8

    - name: Notify on failure
      if: failure()
      env:
        MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        MESSAGE="**Workflow Failed**\n\nWorkflow URL: $GITHUB_RUN_URL\n\nCommit Message: ${{ github.event.head_commit.message }}\n\nCommit Author: ${{ github.event.head_commit.author.name }}"

        curl -H "Content-Type: application/json" -d "{\"text\":\"$MESSAGE\"}" -X POST "$MS_TEAMS_WEBHOOK_URL"

