name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      id: tests
      run: npm test

    - name: Notify Teams
      if: failure()
      run: |
          MSG=${{ steps.tests.outputs.stderr }}
          curl -H 'Content-Type: application/json' -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0078D7",
            "title": "Build Failed",
            "text": "The build failed. Triggered by ${{ github.actor }}. Error: $MSG. Click here for more info."
          }' ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
