name: Workflow
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Your Job 1
        id: job1
        run: |
          npm test
          echo "Starting build..."
          make || (echo "::set-output name=error::Something went wrong" && exit 1)
          echo "Build completed successfully."
          
  notify:
    if: failure() # This job will run if any of the previous jobs fail
    runs-on: ubuntu-latest
    steps:
      - name: Notify Teams on failure
        if: failure()
        run: |
          MSG=$(cat ${{ steps.build.outputs.stderr }})
          curl -H 'Content-Type: application/json' -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0078D7",
            "title": "Build Failed",
            "text": "The build failed. Triggered by ${{ github.actor }}. Error: $MSG. Click here for more info."
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
