name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout code
      id: step1
      run: git checkout master

    - name: Step 2 - Set up Node.js
      id: step2
      run: actions/setup-node@v2

    - name: Step 3 - Install dependencies
      id: step3
      run: npm ci

    - name: Step 4 - Run tests
      id: step4
      run: npm test

    - name: Notify on failure
      if: failure()
      env:
        MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        GITHUB_RUN_URL: ${{ github.run_id }}
      run: |
        MESSAGE="**Workflow Failed**\n\nWorkflow: ${{ github.workflow }}\nRun URL: $GITHUB_RUN_URL\n\nCommit Message: ${{ github.event.head_commit.message }}\nCommit Author: ${{ github.event.head_commit.author.name }}"

        curl -H "Content-Type: application/json" -d "{\"text\":\"$MESSAGE\"}" -X POST "$MS_TEAMS_WEBHOOK_URL"

