name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        npm run

    - name: Notify Teams
      if: failure()
      run: |
        curl -H 'Content-Type: application/json' -d '{"@type": "MessageCard","@context": "http://schema.org/extensions","summary": "Example summary","sections": [{"activityTitle": "CI Failed","activitySubtitle": "CI Workflow","activityImage": "https://teamsnodesample.azurewebsites.net/static/img/image5.png","facts": [{"name": "Repository","value": "${{ github.repository }}"},{"name": "Workflow","value": "${{ github.workflow }}"},{"name": "Action","value": "${{ github.action }}"},{"name": "Event","value": "${{ github.event_name }}"},{"name": "Link to Run","value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}],"markdown": true}]}' ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
