name: Workflow
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Your Job 1
        id: job1
        run: |
          mpm test
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Your Job 2
        id: job2
        run: npm run
  notify:
    if: failure() # This job will run if any of the previous jobs fail
    needs: [job1, job2] # This job depends on all other jobs
    runs-on: ubuntu-latest
    steps:
      - name: Notify Microsoft Teams on error
        run: |
          MSG="Workflow failed on ${{ github.repository }} at commit ${{ github.sha }}. Triggered by ${{ github.actor }} on ${{ github.event_name }}. See ${{ github.event.issue.html_url }} for more details. Error: ${{ needs.job1.outputs.error }} ${{ needs.job2.outputs.error }}"
          PAYLOAD=$(echo '{ "text": "'"$MSG"'" }' | jq -c .)
          curl -H 'Content-Type: application/json' -d "$PAYLOAD" ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
